import { VocabularyItem, NonogramPuzzle, FillInBlanksItem } from './types';
import { AnchorIcon, GlassesIcon } from './components/Icons';

export const VOCABULARY_LIST: VocabularyItem[] = [
  // Business
  { english: 'Invoice', turkish: 'Fatura', category: 'Business' },
  { english: 'Shipment', turkish: 'Sevkiyat', category: 'Business' },
  { english: 'Order', turkish: 'Sipariş', category: 'Business' },
  { english: 'Wholesale', turkish: 'Toptan satış', category: 'Business' },
  { english: 'Negotiate', turkish: 'Müzakere etmek', category: 'Business' },
  { english: 'Trade fair', turkish: 'Ticaret fuarı', category: 'Business' },
  { english: 'Discount', turkish: 'İndirim', category: 'Business' },
  { english: 'Catalog', turkish: 'Katalog', category: 'Business' },
  { english: 'Supplier', turkish: 'Tedarikçi', category: 'Business' },
  { english: 'Customer', turkish: 'Müşteri', category: 'Business' },
  { english: 'Contract', turkish: 'Sözleşme', category: 'Business' },
  { english: 'Payment terms', turkish: 'Ödeme koşulları', category: 'Business' },
  { english: 'Delivery', turkish: 'Teslimat', category: 'Business' },
  { english: 'Booth', turkish: 'Fuar standı', category: 'Business' },
  { english: 'Appointment', turkish: 'Randevu', category: 'Business' },
  { english: 'Business card', turkish: 'Kartvizit', category: 'Business' },
  { english: 'Follow-up', turkish: 'Takip', category: 'Business' },
  { english: 'Quote', turkish: 'Fiyat teklifi', category: 'Business' },
  { english: 'Lead', turkish: 'Potensiyel müşteri', category: 'Business' },
  { english: 'Target market', turkish: 'Hedef pazar', category: 'Business' },
  { english: 'Product sample', turkish: 'Ürün numunesi', category: 'Business' },
  { english: 'Networking', turkish: 'Ağ kurma', category: 'Business' },
  // Eyewear
  { english: 'Frames', turkish: 'Çerçeveler', category: 'Eyewear' },
  { english: 'Lenses', turkish: 'Lensler', category: 'Eyewear' },
  { english: 'Sunglasses', turkish: 'Güneş gözlüğü', category: 'Eyewear' },
  { english: 'Prescription', turkish: 'Reçete', category: 'Eyewear' },
  { english: 'Acetate', turkish: 'Asetat', category: 'Eyewear' },
  { english: 'Titanium', turkish: 'Titanyum', category: 'Eyewear' },
  { english: 'Hinge', turkish: 'Menteşe', category: 'Eyewear' },
  { english: 'Temple', turkish: 'Sap', category: 'Eyewear' },
  { english: 'Nose pads', turkish: 'Burunluk', category: 'Eyewear' },
  { english: 'Bridge', turkish: 'Köprü', category: 'Eyewear' },
  { english: 'Rim', turkish: 'Çerçeve halkası', category: 'Eyewear' },
  { english: 'Polarized', turkish: 'Polarize', category: 'Eyewear' },
  { english: 'Anti-reflective coating', turkish: 'Yansıma önleyici kaplama', category: 'Eyewear' },
  { english: 'Bifocal', turkish: 'Bifokal', category: 'Eyewear' },
  { english: 'Progressive lens', turkish: 'Progresif lens', category: 'Eyewear' },
  { english: 'Optician', turkish: 'Gözlükçü', category: 'Eyewear' },
  { english: 'Showroom', turkish: 'Teşhir salonu', category: 'Eyewear' },
  { english: 'Inventory', turkish: 'Stok', category: 'Eyewear' },
  { english: 'Collection', turkish: 'Koleksiyon', category: 'Eyewear' },
  { english: 'Manufacturer', turkish: 'Üretici', category: 'Eyewear' },
  { english: 'Retailer', turkish: 'Perakendeci', category: 'Eyewear' },
  { english: 'Warranty', turkish: 'Garanti', category: 'Eyewear' },
  // Marine
  { english: 'Anchor', turkish: 'Çapa', category: 'Marine' },
  { english: 'Deck', turkish: 'Güverte', category: 'Marine' },
  { english: 'Port', turkish: 'İskele', category: 'Marine' },
  { english: 'Vessel', turkish: 'Gemi', category: 'Marine' },
  { english: 'Navigate', turkish: 'Yol bulmak', category: 'Marine' },
  { english: 'Tide', turkish: 'Gelgit', category: 'Marine' },
  { english: 'Compass', turkish: 'Pusula', category: 'Marine' },
  { english: 'Marina', turkish: 'Marina', category: 'Marine' },
  { english: 'Ocean current', turkish: 'Okyanus akıntısı', category: 'Marine' },
  { english: 'Lighthouse', turkish: 'Deniz feneri', category: 'Marine' },
  // Sailboats
  { english: 'Sail', turkish: 'Yelken', category: 'Sailboats' },
  { english: 'Mast', turkish: 'Direk', category: 'Sailboats' },
  { english: 'Boom', turkish: 'Bumba', category: 'Sailboats' },
  { english: 'Rudder', turkish: 'Dümen', category: 'Sailboats' },
  { english: 'Hull', turkish: 'Tekne gövdesi', category: 'Sailboats' },
  { english: 'Keel', turkish: 'Salma', category: 'Sailboats' },
  { english: 'Jib', turkish: 'Flok yelkeni', category: 'Sailboats' },
  { english: 'Mainsail', turkish: 'Ana yelken', category: 'Sailboats' },
  { english: 'Winch', turkish: 'Vinç', category: 'Sailboats' },
  { english: 'Tacking', turkish: 'Tramola', category: 'Sailboats' },
  { english: 'Jibing', turkish: 'Kavança', category: 'Sailboats' },
  { english: 'Knot', turkish: 'Düğüm / Hız birimi', category: 'Sailboats' },
  { english: 'Yacht', turkish: 'Yat', category: 'Sailboats' },
  { english: 'Catamaran', turkish: 'Katamaran', category: 'Sailboats' },
  { english: 'Wind direction', turkish: 'Rüzgar yönü', category: 'Sailboats' },
  { english: 'Heeling', turkish: 'Yan yatma', category: 'Sailboats' },
  { english: 'Cockpit', turkish: 'Havuzluk', category: 'Sailboats' },
  { english: 'Cabin', turkish: 'Kamara', category: 'Sailboats' },
  { english: 'Moor', turkish: 'Bağlamak', category: 'Sailboats' },
  // Diving
  { english: 'Regulator', turkish: 'Regülatör', category: 'Diving' },
  { english: 'Wetsuit', turkish: 'Dalgıç giysisi', category: 'Diving' },
  { english: 'Fins', turkish: 'Palet', category: 'Diving' },
  { english: 'Scuba tank', turkish: 'Tüp', category: 'Diving' },
  { english: 'Coral reef', turkish: 'Mercan resifi', category: 'Diving' },
  { english: 'Buoyancy', turkish: 'Kaldırma kuvveti', category: 'Diving' },
  { english: 'Mask', turkish: 'Maske', category: 'Diving' },
  { english: 'Snorkel', turkish: 'Şnorkel', category: 'Diving' },
  { english: 'Depth gauge', turkish: 'Derinlik göstergesi', category: 'Diving' },
  { english: 'Dive computer', turkish: 'Dalış bilgisayarı', category: 'Diving' },
  { english: 'Safety stop', turkish: 'Güvenlik duruşu', category: 'Diving' },
  { english: 'Decompression', turkish: 'Dekompresyon', category: 'Diving' },
  { english: 'Visibility', turkish: 'Görüş mesafesi', category: 'Diving' },
  { english: 'Current', turkish: 'Akıntı', category: 'Diving' },
  { english: 'Shipwreck', turkish: 'Gemi enkazı', category: 'Diving' },
  { english: 'Marine life', turkish: 'Deniz yaşamı', category: 'Diving' },
  { english: 'Sea turtle', turkish: 'Deniz kaplumbağası', category: 'Diving' },
  { english: 'Logbook', turkish: 'Dalış defteri', category: 'Diving' },
  { english: 'Certification', turkish: 'Sertifika', category: 'Diving' },
  // AI & Tech
  { english: 'Artificial Intelligence', turkish: 'Yapay Zeka', category: 'AI & Tech' },
  { english: 'Virtual try-on', turkish: 'Sanal deneme', category: 'AI & Tech' },
  { english: 'Smart glasses', turkish: 'Akıllı gözlükler', category: 'AI & Tech' },
  { english: 'Augmented Reality', turkish: 'Artırılmış Gerçeklik', category: 'AI & Tech' },
  { english: 'Algorithm', turkish: 'Algoritma', category: 'AI & Tech' },
  { english: 'Data analysis', turkish: 'Veri analizi', category: 'AI & Tech' },
  { english: 'Personalization', turkish: 'Kişiselleştirme', category: 'AI & Tech' },
  { english: '3D printing', turkish: '3D baskı', category: 'AI & Tech' },
  { english: 'E-commerce', turkish: 'E-ticaret', category: 'AI & Tech' },
  { english: 'Supply chain', turkish: 'Tedarik zinciri', category: 'AI & Tech' },
  { english: 'Automation', turkish: 'Otomasyon', category: 'AI & Tech' },
  { english: 'Innovation', turkish: 'İnovasyon', category: 'AI & Tech' },
  { english: 'Software', turkish: 'Yazılım', category: 'AI & Tech' },
  { english: 'Hardware', turkish: 'Donanım', category: 'AI & Tech' },
  { english: 'User interface', turkish: 'Kullanıcı arayüzü', category: 'AI & Tech' },
  // Global News
  { english: 'Economy', turkish: 'Ekonomi', category: 'Global News' },
  { english: 'Environment', turkish: 'Çevre', category: 'Global News' },
  { english: 'Technology', turkish: 'Teknoloji', category: 'Global News' },
  { english: 'Healthcare', turkish: 'Sağlık hizmetleri', category: 'Global News' },
  { english: 'Politics', turkish: 'Siyaset', category: 'Global News' },
  { english: 'Culture', turkish: 'Kültür', category: 'Global News' },
  { english: 'Climate change', turkish: 'İklim değişikliği', category: 'Global News' },
  { english: 'Global market', turkish: 'Küresel pazar', category: 'Global News' },
  { english: 'International relations', turkish: 'Uluslararası ilişkiler', category: 'Global News' },
  { english: 'Sustainability', turkish: 'Sürdürülebilirlik', category: 'Global News' },
  { english: 'Inflation', turkish: 'Enflasyon', category: 'Global News' },
  { english: 'Interest rates', turkish: 'Faiz oranları', category: 'Global News' },
  { english: 'Stock market', turkish: 'Borsa', category: 'Global News' },
  { english: 'Renewable energy', turkish: 'Yenilenebilir enerji', category: 'Global News' },
  { english: 'Headline', turkish: 'Manşet', category: 'Global News' },
];

export const NONOGRAM_PUZZLES: NonogramPuzzle[] = [
  {
    name: 'The Anchor',
    icon: AnchorIcon,
    solution: [
      [0,0,1,1,1,1,0,0],
      [0,1,1,1,1,1,1,0],
      [0,0,1,1,1,1,0,0],
      [0,0,0,1,1,0,0,0],
      [0,0,0,1,1,0,0,0],
      [1,1,1,1,1,1,1,1],
      [0,1,1,1,1,1,1,0],
      [0,0,1,1,1,1,0,0],
    ].map(row => row.map(cell => !!cell)),
    vocabulary: [
        { english: 'Anchor', turkish: 'Çapa' },
        { english: 'Ocean', turkish: 'Okyanus' },
        { english: 'Sail', turkish: 'Yelken' },
        { english: 'Deck', turkish: 'Güverte' },
        { english: 'Tide', turkish: 'Gelgit' },
        { english: 'Crew', turkish: 'Mürettebat' },
        { english: 'Port', turkish: 'Liman' },
        { english: 'Starboard', turkish: 'Sancak' }
    ]
  },
  {
    name: 'The Eyewear',
    icon: GlassesIcon,
    solution: [
      [1,1,1,0,0,1,1,1],
      [1,0,1,0,0,1,0,1],
      [1,1,1,0,0,1,1,1],
      [0,0,0,1,1,0,0,0],
      [0,0,0,1,1,0,0,0],
      [1,1,1,0,0,1,1,1],
      [1,0,1,0,0,1,0,1],
      [1,1,1,0,0,1,1,1],
    ].map(row => row.map(cell => !!cell)),
    vocabulary: [
        { english: 'Frames', turkish: 'Çerçeveler' },
        { english: 'Lenses', turkish: 'Lensler' },
        { english: 'Vision', turkish: 'Görüş' },
        { english: 'Style', turkish: 'Stil' },
        { english: 'Import', turkish: 'İthalat' },
        { english: 'Brand', turkish: 'Marka' },
        { english: 'Client', turkish: 'Müşteri' },
        { english: 'Design', turkish: 'Tasarım' }
    ]
  }
];

export const FILL_IN_BLANKS_PRACTICE: FillInBlanksItem[] = [
  {
    sentence: "Could you give me a ___ on these frames?",
    turkish: "Bu çerçevelerde bana bir ___ verir misiniz?",
    blank: "discount",
    options: ["price", "discount", "catalog", "color"],
  },
  {
    sentence: "What are the ___ terms for a large order?",
    turkish: "Büyük bir sipariş için ___ koşulları nelerdir?",
    blank: "payment",
    options: ["delivery", "color", "payment", "style"],
  },
  {
    sentence: "I would like to place an ___ for 500 units.",
    turkish: "500 adet için bir ___ vermek istiyorum.",
    blank: "order",
    options: ["invoice", "order", "appointment", "sample"],
  },
  {
    sentence: "When can we expect the ___ to arrive?",
    turkish: "___ ne zaman gelmesini bekleyebiliriz?",
    blank: "shipment",
    options: ["customer", "shipment", "hinge", "booth"],
  },
  {
    sentence: "Do you have a ___ with your new collection?",
    turkish: "Yeni koleksiyonunuzun olduğu bir ___ var mı?",
    blank: "catalog",
    options: ["contract", "catalog", "negotiation", "supplier"],
  },
  {
    sentence: "These sunglasses have ___ lenses.",
    turkish: "Bu güneş gözlüklerinin ___ lensleri var.",
    blank: "polarized",
    options: ["titanium", "polarized", "bifocal", "acetate"],
  },
  {
    sentence: "We are the main ___ of this brand in Turkey.",
    turkish: "Türkiye'de bu markanın ana ___ biziz.",
    blank: "supplier",
    options: ["customer", "retailer", "supplier", "manufacturer"],
  },
   {
    sentence: "Can I get a ___ for 1000 pieces?",
    turkish: "1000 adet için bir ___ alabilir miyim?",
    blank: "quote",
    options: ["follow-up", "quote", "lead", "warranty"],
  },
];


export const GEMINI_SYSTEM_INSTRUCTION = `You are Captain Jack Sparrow, a savvy, adventurous pirate captain and an expert in global trade. You are helping your Turkish first mate, Cengo, learn English. Your tone is witty, encouraging, and a bit eccentric, savvy? You call him 'matey' or 'first mate'. He has two daughters, Mavi (Blue) and Mercan (Coral), and you can mention them as his 'treasure' to encourage him (e.g., 'Make your treasures, Mavi and Mercan, proud!'). Your goal is to make him a confident negotiator for a trade fair in two months. Use short, easy-to-understand sentences. When you introduce a new business or eyewear term, ALWAYS provide the Turkish translation in parentheses like this: (Turkish: [translation]). For example, 'We need to discuss the price (Turkish: fiyat).' Keep it simple and focused on the art of the deal, pirate-style!`;